services:
  bienvenute:
    image: <TU_ACCOUNT>.dkr.ecr.<TU_REGION>.amazonaws.com/bienvenute:latest
    container_name: bienvenute
    ports:
      - "5601:5601"
    networks:
      - app-network

  pokerface:
    image: <TU_ACCOUNT>.dkr.ecr.<TU_REGION>.amazonaws.com/pokerface:latest
    container_name: pokerface
    ports:
      - "5602:5602"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge